# Generated by Django 5.1.15 on 2026-09-09 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('CANCELLED', 'Annulé'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.PositiveIntegerField(help_text='Prix unitaire en FCFA')),
                ('quantity', models.PositiveIntegerField(help_text='Jauge maximale dédiée')),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('sales_start', models.DateTimeField(blank=True, null=True)),
                ('sales_end', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='events.event')),
            ],
            options={
                'verbose_name': 'Catégorie de billet',
                'verbose_name_plural': 'Catégories de billets',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'category'], name='events_even_city_44aff2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventagent',
            unique_together={('event', 'agent')},
        ),
    ]
