# Generated by Django 5.1.15 on 2026-09-11 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_full_name', models.CharField(max_length=150)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PAID', 'Payée'), ('FAILED', 'Échouée'), ('REFUNDED', 'Remboursée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CARD', 'Carte bancaire'), ('MTN_MOMO', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('ORANGE_MONEY', 'Orange Money')], max_length=20, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=120)),
                ('total_amount', models.PositiveIntegerField(help_text='Montant total en FCFA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField(help_text="Prix figé au moment de l'achat")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.order')),
                ('ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.ticketcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('VALID', 'Valide'), ('SCANNED', 'Scanné'), ('CANCELLED', 'Annulé')], default='VALID', max_length=20)),
                ('holder_first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('holder_last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('holder_profession', models.CharField(blank=True, max_length=40, verbose_name='Profession')),
                ('holder_country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('holder_city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('holder_photo', models.ImageField(blank=True, null=True, upload_to='tickets/holders/', verbose_name='Photo')),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.order')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('ticket_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.ticketcategory')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event', 'status'], name='tickets_ord_event_i_3c3433_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer_email'], name='tickets_ord_buyer_e_5882db_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
    ]
