# Generated by Django 5.1.15 on 2026-09-15 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('VALID', 'Valide'), ('ALREADY_SCANNED', 'Déjà scanné'), ('NOT_FOUND', 'Billet inexistant'), ('WRONG_EVENT', 'Mauvais événement'), ('CANCELLED_TICKET', 'Billet annulé')], max_length=20)),
                ('scanned_at', models.DateTimeField()),
                ('offline_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='events.event')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='tickets.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'scanned_at'], name='scanner_sca_event_i_0daa2a_idx')],
            },
        ),
    ]
